### ISSUE TITLE
Unrecognised subcommand 'client'

### ISSUE THREAD

**Issue by danieleavitabile** [chipsenkbeil/distant.nvim#104]
I have installed the plugin using the recommended default Packer setup (at the end of the message).  I have installed Distant as recommended in your latest YouTube video. When I issue DistantLaunch I get the following message

error: unrecognized subcommand 'client'

I wonder if you have any ideas as to why this may be the case, or what to try to get unstuck. 

````
   use {
    'chipsenkbeil/distant.nvim',
    branch = 'v0.2',
    config = function()
      require('distant').setup {
        -- Applies Chip's personal settings to every machine you connect to
        --
        -- 1. Ensures that distant servers terminate with no connections
        -- 2. Provides navigation bindings for remote directories
        -- 3. Provides keybinding to jump into a remote file's parent directory
        ['*'] = require('distant.settings').chip_default()
      }
    end
  }
````

**Comment by chipsenkbeil** [comment]
@danieleavitabile if you run `:DistantClientVersion` what does it print out? If that doesn't work, what do you get from running `~/.local/share/nvim/distant.nvim/bin/distant --version`?

I'm guessing that you actually downloaded a version of distant that is too new for the v0.2 branch. The v0.3 branch is nearly ready and also fixed a bug where checks for version  mismatches wouldn't stop you from downloading a newer version.

**Comment by danieleavitabile** [comment]
Thanks @chipsenkbeil and sorry to cause trouble. I am on distant 0.20.0-alpha.8 (and I was only offered "alpha" versions do download). If I can read somewhere how to uninstall and install again an appropriate version I can go ahead

**Comment by chipsenkbeil** [comment]
No trouble at all! This software is still in flux and has pain points, and the best way to get through them is to ask :) Ideally once v0.3 comes out, it'll be locked to a proper version.

For v0.2, you want `0.20.0-alpha.4` as that's the supported version. To re-install distant that was installed using `:DistantInstall`, you have two options:

1. Run `:DistantInstall reinstall` to trigger overwriting your downloaded binary.
2. Delete the binary located at `~/.local/share/nvim/distant.nvim/bin/distant` and run `:DistantInstall`.

Either way should let you pick a binary version, and this time you want to pick `0.20.0-alpha.4`.

**Comment by danieleavitabile** [comment]
Thanks, I have now successfully installed a working distant version. Looking forward to version 0.3 and thanks for your help, and for developing the package.
