### ISSUE TITLE
DistantLaunch Failed

### ISSUE THREAD

**Issue by ihaohe** [chipsenkbeil/distant.nvim#111]
When I try to use the cmd ":DistantLaunch servername" , the error occurs. It seems i've already conncted to the server but distant cmd failed. Is it the configuration error or something else?  Any suggestions will be fine. Thanks

![image](https://github.com/chipsenkbeil/distant.nvim/assets/41662686/fc6f8dbe-b89e-4a2d-ae41-b1a628724c24)

**Comment by chipsenkbeil** [comment]
1. What version of the plugin are you using? v0.2? v0.3?
2. What version of distant are you using? You can check via `:DistantClientVersion`
3. Can you share the full command you're using for `:DistantLaunch`?
