### ISSUE TITLE
How to install distant.nvim v3.0?

### ISSUE THREAD

**Issue by hachi-27** [chipsenkbeil/distant.nvim#112]
Hi,

## Intro
As per our last discussion in #94 , I was unable to make it work at all and then I got busy in another project. So, now I'm starting fresh to try out distant.nvim again with the lastest v3.0 branch. However, I'm unable to get it installed properly.

```use {
  'chipsenkbeil/distant.nvim',
  branch = 'v0.2',
  config = function()
    require('distant').setup {
      -- Applies Chip's personal settings to every machine you connect to
      --
      -- 1. Ensures that distant servers terminate with no connections
      -- 2. Provides navigation bindings for remote directories
      -- 3. Provides keybinding to jump into a remote file's parent directory
      ['*'] = require('distant.settings').chip_default()
    }
  end
}
```

## Reason
 Because of the present of ``distant.settings``. Apparently, this is not avaiable in v3.0. So what should I do regarding this? Please share your thoughts.
 
 Thanks

**Comment by chipsenkbeil** [comment]
@hachi-27 can you take a look at the documentation I've just added to https://distant.dev/ ? I'm in the progress of writing it, but it should demonstrate installing and configuring the plugin.

Specifically, check out these sections:

- https://distant.dev/editors/neovim/quickstart/
- https://distant.dev/editors/neovim/setup/

**Comment by chipsenkbeil** [comment]
Closing this out as the documentation is now covered both in the v0.3 branch's README and on the website as linked earlier.
