### ISSUE TITLE
Plugin commands not found by neovim

### ISSUE THREAD

**Issue by Duckilicious** [chipsenkbeil/distant.nvim#121]
Hey,

I'd like to check out your plugin as it feels like it will fit my workflow really nicely.

The current issue I have is that the current plugins commands are not recognized by nvim.
I bisected the issue to commit: 
```
commit 72273dc5fc7c12c487d59e972e33c3634a41a7b2
Author: Chip Senkbeil <chip@senkbeil.org>
Date:   Thu Jun 1 03:31:09 2023 -0500

    Rewrite plugin in preparation for v0.3 (#99
```
The error:
```
E492: Not an editor command: DistantInstall
```

Platform: OSX
Nvim version:  9.2

I also tried installing nvim 8.0 and 8.3 and the issue persists.

Output of `health`:

```
distant: require("distant.health").check()

distant.nvim ~
- OK distant installed
- OK distant version 0.20.0 meets minimum requirement of 0.20.0
```

In commits before the above mentioned commit I get errors on the `distant client` command not existing I guess I have to install an older version of distant to get rid of those.

This is as far as I got, I'd appreciate your help in debugging this.

**Comment by chipsenkbeil** [comment]
Hey there! Version `v0.3` of the plugin uses distant `0.20.0`. That's the ideal setup you want.

Are you saying that commands like `:DistantInstall` and `:DistantLaunch` cannot be found? If so, have you made sure to call `require("distant"):setup()` first? The setup function needs to be called before using distant, and it's what sets up all of the vim commands, autocommands, and some other details within neovim.

**Comment by Duckilicious** [comment]
Now that's embarrassing :)

Thanks!

**Comment by KELs7** [comment]
@chipsenkbeil  I am having this same issue. I installed with lazy.nvim using this from docs

```
{
    'chipsenkbeil/distant.nvim', 
    branch = 'v0.3',
    config = function()
        require('distant'):setup()
    end
}
```
`E492: Not an editor command: DistantInstall`

**Comment by KELs7** [comment]
ok the fix is to add the commands yourself. Can you kindly update lazy installation config? others might not know what to do

```
{
    "chipsenkbeil/distant.nvim",
    branch = "v0.3",
    cmd = {
      "DistantInstall",
      "Distant",
      "DistantLaunch",
      "DistantSessionInfo",
      "DistantConnect",
      "DistantCheckHealth",
      "DistantClientVersion",
    },
    config = function()
      require("distant"):setup()
    end,
  }
  ```
