### ISSUE TITLE
Telescope & NeoTree

### ISSUE THREAD

**Issue by josh-ramer** [chipsenkbeil/distant.nvim#123]
Should distant.nvim work with Telescope & NeoTree already? Am I missing some configuration? I saw some telescope files in the repository from ~5 months ago & hoped that might be coming soon. If it's not in the plans, maybe it's something I could try to figure out? Distant.nvim looks like it solves the remote/container development problem, I just need to get it well integrated into my Nvim flow to justify not just copying Nvim into every container or machine I come across. 

In any case, thank you so much for creating such a thoughtful technology & taking it to another level.

Regards

**Comment by josh-ramer** [comment]
I see another issue shedding some light on the state of the telescope capability. I'll see if their config can get me going.

**Comment by chipsenkbeil** [comment]
@josh-ramer feel free to start a discussion or comment on the issue you're describing if you have questions 😄 I worked on the telescope integration on-and-off, and it still seems a bit buggy. I think I haven't implemented the asynchronous logic for telescope quite properly, so any help you can give there is appreciated.

If you hit any bugs with the search logic from distant, it may mean we need to get a patch into the distant binary, just as a heads up. I've been building the binary along the same time as this plugin.

As for neotree, feel free to submit a PR for it if you get an implementation working!
