### ISSUE TITLE
:DistantInstall Downloads Incompatible Distant Server Version When Using "Download Prebuilt Binary"

### ISSUE THREAD

**Issue by EightBitBoot** [chipsenkbeil/distant.nvim#132]
As of writing, the minimum cli version supported by the plugin is `v0.20.0`, and while the prebuilt binary download version selection menu shows `v0.20.0`, it actually fetches the binary for `v0.20.0-alpha...`.

This is because the github releases api "correctly" returns the alpha as the latest release when querying ﻿`https://api.github.com/repos/chipsenkbeil/distant/releases` (element 0 named `latest` in the returned json array).  Meanwhile, the correct version is sitting in element 1 and labeled `v0.20.0`.

A simple fix for this could be to add a parameter to `lua/distant-core/cli.lua:M:install(...)` along the lines of `allow_alphas` that gets passed down the stack to the worker functions and defaults to false.  These worker functions could then, in turn, switch their behavior based on this option.

However, I'm not sure if this is in line with how you, the author(s), want to handle this so I'm not directly making a pull request.

Version Info:

2023 Macbook Pro M2 Pro
Macos Sonoma 14.4
Nvim Version v0.9.5
Installed With vim-plug (version unknown)
Installed via the (lua) command in `~/.config/nvim/init.nvim` `Plug("chipsenkbeil/distant.nvim", {["branch"]="v0.3", ["do"]=":lua require('distant'):setup()"})`
distant.nvim commit (taken from `~/.local/share/nvim/plugged/distant.nvim`) `de7288b`

**Comment by chipsenkbeil** [comment]
I'm happy to receive a parameter to show or not show alphas. I'd been busy working on [org-roam.nvim](https://github.com/chipsenkbeil/org-roam.nvim), but I'm around now to review submissions. 😄

**Comment by chipsenkbeil** [comment]
@EightBitBoot got around to testing this and I think I rolled out a fix. Try using the latest commit: https://github.com/chipsenkbeil/distant.nvim/commit/823267cf3b77cf9a7ae28454926eabc18fec1ba0.

There was a bug where hidden choices (for example, the alpha download options) weren't being factored in when a choice was made. So it was picking the wrong binary like you encountered.

**Comment by chipsenkbeil** [comment]
Closing out as resolved per https://github.com/chipsenkbeil/distant.nvim/commit/823267cf3b77cf9a7ae28454926eabc18fec1ba0.
