### ISSUE TITLE
Is there any way to use local LSP when `DistantConnect` via ssh?

### ISSUE THREAD

**Issue by realzhujunhao** [chipsenkbeil/distant.nvim#134]
As title suggests.

**Comment by chipsenkbeil** [comment]
No at the moment. Distant works by proxying input and output from remote programs to your local machine, not the other way around.

For a language server, you need access to the full codebase for navigation, hints, etc. To do that locally while using a remote codebase, we'd have to intercept system calls for a process, send them over the network, get results, and send back.

You'll have a faster and more successful time using sshfs if local language servers is what you're after. An equivalent to sshfs for distant was planned, but not implemented yet.
