### ISSUE TITLE
How does this differ from sshfs+neovim?

### ISSUE THREAD

**Issue by reportaman** [chipsenkbeil/distant.nvim#33]
There is a video on how to use sshfs+neovim to edit files on a remote machine: https://youtu.be/0fAygjWHpdM. How does distant.nvim differ from that?

**Comment by chipsenkbeil** [comment]
@reportaman, here's a couple of the primary differences that come to mind at the moment:

1. **Filesystem**: sshfs is built using FUSE, meaning that you need support for it as a userland filesystem. distant.nvim requires no special filesystem as the file contents are only reflected in buffers. Anything you read goes into a buffer and anything you write gets transmitted across the network.
2. **Program locations**: distant supports running programs on the remote machine, colocated with your files. Language servers would run on the remote machine, for instance. When using sshfs to mount the remote file system on your local machine, you would then run programs locally and point them to the mounted files. 
    * With distant, you are leveraging the resources of a remote machine. This can be advantageous if you want to perform CPU or GPU intensive operations without heavily impacting your local machine.
    * With sshfs, you are leveraging the resources of a local machine. Depending on what you're doing, this can be much more expensive. If a program needs to access the filesystem frequently, this would transmit a lot of requests over the network, especially if working over a large set of files. With distant, all of the filesystem operations would happen directly on the remote machine and only the program's output would be transmitted over the network.

There are other technical differences, but the distinctions above are - at the moment - the differences that stand out. In some cases, using sshfs might be preferred, but for my use personally and at work this is the preferred method. :)

If you want to think of what this more closely relates to, then take a look at [VS Code Remote Development](https://code.visualstudio.com/docs/remote/remote-overview) or the formerly-active [Nuclide](https://github.com/facebookarchive/nuclide).

**Comment by chipsenkbeil** [comment]
@reportaman feel free to open additional issues if you have any more questions. :) Going to close this one out, although we can continue to converse here if there's anything you want to dive into with regards to my answers!

**Comment by Kailian-Jacy** [comment]
Is there any possibility decouple these two contributions?

In some cases, using FUSE is acceptable and provide a neat and strong abstract to other nvim features. Despite great charm of revoking lsp remotely, I find it very hard to integrate into my workflows as if files are local. Like searching plugins, project managing plugins, etc. If we can provide combination of sshfs and remote lsp, they all works out. 

Btw, (I'm not a file system expert and knows little about fuse), Why are we avoiding involving FUSE? On MacOS, there are some projects going on providing convenient fuse extension that does not require kernel security extension, comes handy (*https://github.com/macos-fuse-t/fuse-t*).
