### ISSUE TITLE
Support spawning a remote shell

### ISSUE THREAD

**Issue by chipsenkbeil** [chipsenkbeil/distant.nvim#44]
Dependent on https://github.com/chipsenkbeil/distant/issues/1 being integrated into `distant-lua` and https://github.com/neovim/neovim/issues/16079 having some resolution to enable this plugin to be able to communicate as the PTY master.

**Comment by hhoeflin** [comment]
This would be very interesting, depending on how easy to open certain environments (e.g. conda etc)!

**Comment by chipsenkbeil** [comment]
> This would be very interesting, depending on how easy to open certain environments (e.g. conda etc)!

Yeah, this should work for any shell-based setup. You'd be able to have anaconda configured on a remote machine or docker container and then point a shell to it to work with a python repl or something.

**Comment by zippeurfou** [comment]
Yes this would def be nice for python users. Not sure what’s the workaround if you have conda remotely right now.

**Comment by chipsenkbeil** [comment]
@zippeurfou this is available in the v0.2 branch. You can do something like `:DistantShell python` to start a python shell.

**Comment by chipsenkbeil** [comment]
This is now integrated into v0.2 officially and rolled out to the master branch.
