### ISSUE TITLE
Offering different public keys

### ISSUE THREAD

**Issue by david-perez** [chipsenkbeil/distant.nvim#51]
Thanks for this useful plugin and your talk in VimConf.

I see that the `distant` binary [has support for setting `identity_files`](https://github.com/chipsenkbeil/distant/blob/0f56669ccd386ece67e3da4560e16cbd79b6d8ef/distant-ssh2/src/lib.rs#L60).

However, I can't figure out what to feed the `:DistantLaunch` command so that it [parses](https://github.com/chipsenkbeil/distant.nvim/blob/9f8a802a6a5ca1a95b8db68a2b78ffa28efbcb65/lua/distant/command.lua#L96-L96) the `ssh.identity_files` input into something that `mlua` can smoothly deserialize into a `Vec<PathBuf>`, e.g.

```
:DistantLaunch my.host.com ssh.identity_files=["~/.ssh/id_rsa_distant"]
```

**Comment by chipsenkbeil** [comment]
@david-perez I think this is a limitation of the [input parser for commands](https://github.com/chipsenkbeil/distant.nvim/blob/master/lua/distant/command.lua#L6) not supporting lists.

I think you can get away with adding a configuration to your host during setup and provide a list in lua, though.

```lua
setup {
    ['*'] = {
        ssh = {
            identity_files = { "/path/to/.ssh/id_rsa_distant" },
        }
    }
}
```

**Comment by chipsenkbeil** [comment]
Closing out as an outdated issue. With v0.3 being the new branch, feel free to open a new issue against it if this is still a problem.
