### ISSUE TITLE
Help connecting using ssh config and ssh alias

### ISSUE THREAD

**Issue by Soundtoxin** [chipsenkbeil/distant.nvim#58]
When using netrw I can use ssh aliases like `mainserver` and open `scp://mainserver/` where `mainserver` is configured in `~/.ssh/config` with a username, hostname, and key file to use. This also makes multi-hop ssh connections trivial. I couldn't seem to do this with distant.nvim.

**Comment by chipsenkbeil** [comment]
I was assuming this would work as we're using [wezterm-ssh](https://github.com/wez/wezterm) to power the ssh logic. There may be something misconfigured on my end.

Just checking, @wez this should be supported by your lib, right? I'm pulling in a config for a host as defined here: https://github.com/chipsenkbeil/distant/blob/master/distant-ssh2/src/lib.rs#L209

**Comment by Soundtoxin** [comment]
It's possible I'm just trying the wrong thing. When prompted for a host, I gave my ssh alias instead. I actually haven't been able to figure out how to make a connection so far. If this is really supported, then I guess I should open an issue about documentation instead.

**Comment by wez** [comment]
It should work, but we did have https://github.com/wez/wezterm/issues/1196 recently which may be a factor.  It would be helpful if you shared the relevant portions of your `~/.ssh/config` to confirm.

**Comment by Soundtoxin** [comment]
```
Host gizuko
    user guest
    HostName izuko
    IdentityFile ~/.ssh/id_ed25519
    ServerAliveInterval 15
    ServerAliveCountMax 3
```

I tried
`:DistantLaunch gizuko` and get

```
SSH-2.0-OpenSSH_8.4p1 Debian-3
callback error
stack traceback:
^I[C]: in ?
^I[C]: in function 'pcall'
^I...nvim/autoload/distant.nvim/lua/distant/editor/launch.lua:81: in function 'load'
^I...nvim/autoload/distant.nvim/lua/distant/editor/launch.lua:67: in function 'launch'
^I...onfig/nvim/autoload/distant.nvim/lua/distant/command.lua:177: in function 'launch'
^I[string ":lua"]:1: in main chunk
caused by: failed to lookup address information: Name or service not known
callback error
stack traceback:
^I[C]: in ?
^I[C]: in function 'pcall'
^I...nvim/autoload/distant.nvim/lua/distant/editor/launch.lua:81: in function 'load'
^I...nvim/autoload/distant.nvim/lua/distant/editor/launch.lua:67: in function 'launch'
^I...onfig/nvim/autoload/distant.nvim/lua/distant/command.lua:177: in function 'launch'
^I[string ":lua"]:1: in main chunk
caused by: failed to lookup address information: Name or service not known
```

or when I try `:DistantConnect gizuko` I get `Missing port`

I tried putting `22` after it and then I'm asked for a distant key. Not sure what that is. I guess I just wanted it to work like netrw and it seems pretty different.

**Comment by chipsenkbeil** [comment]
Ah, I think there might be a little bit of confusion. `DistantConnect` is designed to only be used when connecting to a distant server. It's asking for a key as the distant server requires an authentication key.

If you're wanting to just use ssh to power remote edits, programs, etc, then you need to set the mode to *ssh* instead of *distant* via `:DistantLaunch gizuko mode=ssh` or specifying the mode in your configuration when setting up distant via

```lua
require('distant').setup {
    ['*'] = vim.tbl_deep_extend('force', require('distant.settings').chip_default(), {
        mode = 'ssh',
    })
}
```

**Comment by Soundtoxin** [comment]
Ah, I see. I didn't know this used something besides ssh by default.

I gave `:DistantLaunch gizuko mode=ssh` a try and I get some errors still that the name or service isn't known.

```
SSH-2.0-OpenSSH_8.4p1 Debian-3                                                                                                                      
callback error
stack traceback:
^I[C]: in ?
^I[C]: in function 'pcall'
^I...nvim/autoload/distant.nvim/lua/distant/editor/launch.lua:81: in function 'load'
^I...nvim/autoload/distant.nvim/lua/distant/editor/launch.lua:67: in function 'launch'
^I...onfig/nvim/autoload/distant.nvim/lua/distant/command.lua:177: in function 'launch'
^I[string ":lua"]:1: in main chunk
caused by: failed to lookup address information: Name or service not known
callback error
stack traceback:
^I[C]: in ?
^I[C]: in function 'pcall'
^I...nvim/autoload/distant.nvim/lua/distant/editor/launch.lua:81: in function 'load'
^I...nvim/autoload/distant.nvim/lua/distant/editor/launch.lua:67: in function 'launch'
^I...onfig/nvim/autoload/distant.nvim/lua/distant/command.lua:177: in function 'launch'
^I[string ":lua"]:1: in main chunk
caused by: failed to lookup address information: Name or service not known
```
>or specifying the mode in your configuration when setting up distant via
Do I need to do something besides install this plugin if ssh is all I'm interested in? I don't think I have set up "distant" at all. (and I'm not sure which end I would do that on... maybe every end)

**Comment by chipsenkbeil** [comment]
> Do I need to do something besides install this plugin if ssh is all I'm interested in? I don't think I have set up "distant" at all. (and I'm not sure which end I would do that on... maybe every end)

Nope! The plugin prompts you to install the needed library on first use on your local machine. The distant binary only needs to be on remote computers if you want its features. For just ssh, you've got everything you need. 

I *think* this might need investigation on the side of wezterm-ssh as I only do a DNS lookup when connecting to a distant server, otherwise I leave everything to the ssh library. 

@wez do you know if the lib should work with this configuration? I can double check my  side to see if I am doing anything else that might cause this error.

**Comment by chipsenkbeil** [comment]
Turns out I do have a call to resolve the input as a dns entry when using ssh mode: https://github.com/chipsenkbeil/distant/blob/master/distant-ssh2/src/lib.rs#L491

This is something that will need to be fixed/changed to support your use case, @Soundtoxin. So you can safely say that this is a bug! @wez, believe we should be good from a wezterm-ssh perspective for the moment. :)

**Comment by chipsenkbeil** [comment]
https://github.com/chipsenkbeil/distant/commit/669d4196720557e031d61793aebe29eeae254925 may be the fix for this.

**Comment by nguyentritai2906** [comment]
> [chipsenkbeil/distant@669d419](https://github.com/chipsenkbeil/distant/commit/669d4196720557e031d61793aebe29eeae254925) may be the fix for this.

This fix it. But I have to reinstall the plugin to download the new prebuild Rush library. Is it possible to auto check and download the new prebuild when calling DistantInstall?

**Comment by chipsenkbeil** [comment]
> > [chipsenkbeil/distant@669d419](https://github.com/chipsenkbeil/distant/commit/669d4196720557e031d61793aebe29eeae254925) may be the fix for this.
> 
> This fix it. But I have to reinstall the plugin to download the new prebuild Rush library. Is it possible to auto check and download the new prebuild when calling DistantInstall?

You should be able to run `:DistantInstall reload` to trigger to prompt to download the library again. See [the documentation](https://github.com/chipsenkbeil/distant.nvim/blob/master/doc/distant.txt#L258) for more information on it.

Unfortunately, there's no easy way to force Lua to reload a C library, so you'll still need to restart neovim after running `:DistantInstall reload`.

Alternatively, you can delete the `distant_lua.so` file that gets downloaded into the root of the `lua/` folder of the plugin to trigger the prompt again.

**Comment by Midren** [comment]
@chipsenkbeil 
It did help with mode=ssh for me too, but is it possible to make it work for mode=distant ? Currently, after calling `:DistantInstall ubuntu_linode` I get next error:

```
stack traceback:
^I[C]: in ?
^I[C]: in function 'pcall'
^I.../.vim/plugged/distant.nvim/lua/distant/editor/launch.lua:81: in function 'load'
^I.../.vim/plugged/distant.nvim/lua/distant/editor/launch.lua:67: in function 'launch'
^I...shchuk/.vim/plugged/distant.nvim/lua/distant/command.lua:177: in function 'launch'
^I[string ":lua"]:1: in main chunk
caused by: ubuntu_linode needs to be resolvable outside of ssh: failed to lookup address information: nodename
 nor servname provided, or not known
callback error
stack traceback:
^I[C]: in ?
^I[C]: in function 'pcall'
^I.../.vim/plugged/distant.nvim/lua/distant/editor/launch.lua:81: in function 'load'
^I.../.vim/plugged/distant.nvim/lua/distant/editor/launch.lua:67: in function 'launch'
^I...shchuk/.vim/plugged/distant.nvim/lua/distant/command.lua:177: in function 'launch'
^I[string ":lua"]:1: in main chunk
caused by: ubuntu_linode needs to be resolvable outside of ssh: failed to lookup address information: nodename
 nor servname provided, or not known
```

**Comment by chipsenkbeil** [comment]
> @chipsenkbeil It did help with mode=ssh for me too, but is it possible to make it work for mode=distant?

At the moment, no. Connecting to a distant server requires us to be able to resolve a name like ubuntu_linode outside of ssh. We'd need to build an ssh config parser to know what ubuntu_linode references.

I'll close this out and we can make a new issue to track.
