### ISSUE TITLE
Lsp break

### ISSUE THREAD

**Issue by Midren** [chipsenkbeil/distant.nvim#62]
Local:
nvim version: v0.7.0-dev+2680-gcaffee0b6
OS: Mac OS 12.2.1
distant: 0.15.1

Remote:
nvim version: v0.7.0-dev
OS: Ubuntu 21.10
distant: 0.15.1

*Problem:*
I have settled up lsp as:
```
['Test project'] = {
    cmd = { '/home/midren/.local/share/nvim/lsp_servers/python/node_modules/pyright/langserver.index.js', '--stdio'  },
    filetypes = { 'python' },
    root_dir = '/home/midren/new_dir/'
}
```

After I connected to remote via DistantLaunch, lsp is started, but after that it breaks with next error:
```
"LSP[1]"	"on_error"	{  code = "READ_ERROR",  err = "callback error\nstack traceback:\n\t[C]: in function 'poll'\n\t[string \"_mlua_async_poll\"]:5: in main chunk\ncaused by: broken pipe"}
```
I have attached the logs from lsp and from distant with log level trace:

[distant.log](https://github.com/chipsenkbeil/distant.nvim/files/8218283/distant.log)
[lsp.log](https://github.com/chipsenkbeil/distant.nvim/files/8218274/lsp.log)

**Comment by chipsenkbeil** [comment]
Just to make sure, this is using distant mode and not ssh mode?

**Comment by Midren** [comment]
I tried both actually )

**Comment by chipsenkbeil** [comment]
@Midren I'm planning to release v0.2 of the plugin with a new version of distant in the coming weeks. I'll comment here again when it's done. It may fix your issues.

**Comment by chipsenkbeil** [comment]
Closing out as an outdated issue. With v0.3 being the new branch, feel free to open a new issue against it if this is still a problem.
