### ISSUE TITLE
Spawning distant failed

### ISSUE THREAD

**Issue by SmiteshP** [chipsenkbeil/distant.nvim#64]
Hey!

I ran `DistantInstall` and installed 0.15.1 version
And after that while trying to run `DistantLaunch <vm_address>.com ssh.user=<my_username>` I got this error. Any idea how to fix this?

```
callback er
ror
stack traceback:
^I[C]: in ?
^I[C]: in function 'pcall'
^I.../packer/start/distant.nvim/lua/distant/editor/launch.lua:81: in function 'load'

^I.../packer/start/distant.nvim/lua/distant/editor/launch.lua:67: in function 'launc
h'
^I...e/pack/packer/start/distant.nvim/lua/distant/command.lua:177: in function 'laun
ch'
^I[string ":lua"]:1: in main chunk
caused by: Spawning distant failed [???]: zsh:1: command not found: distant
callback error
stack traceback:
^I[C]: in ?
^I[C]: in function 'pcall'
^I.../packer/start/distant.nvim/lua/distant/editor/launch.lua:81: in function 'load'

^I.../packer/start/distant.nvim/lua/distant/editor/launch.lua:67: in function 'launc
h'
^I...e/pack/packer/start/distant.nvim/lua/distant/command.lua:177: in function 'laun
ch'
^I[string ":lua"]:1: in main chunk
caused by: Spawning distant failed [???]: zsh:1: command not found: distant
```

**Comment by SmiteshP** [comment]
I am trying to remote into a Centos 7 machine.

Output of `cat /etc/os-release`

```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

**Comment by chipsenkbeil** [comment]
@SmiteshP the error message of importance is at the bottom of that entire blob.

> caused by: Spawning distant failed [???]: zsh:1: command not found: distant

Starting up the server on your remote machine can sometimes struggle to find the `distant` binary, even if it's on your PATH on the server. Try explicitly setting the distant binary's location via

```lua
require('distant').setup {
    ['my.server.address'] = {
        distant = {
            bin = '/path/to/distant',
        },
    },
}
```

**Comment by SmiteshP** [comment]
@chipsenkbeil Do we have to explicitly install distant on remote machine? If so, how do we do it?

**Comment by SmiteshP** [comment]
@chipsenkbeil 
I would be great if distant.nvim could handle installing the distant binary on the remote machine. It could curl a bash script to install the pre-built binaries. I would make the experience really seamless. :)

**Comment by chipsenkbeil** [comment]
> @chipsenkbeil I would be great if distant.nvim could handle installing the distant binary on the remote machine. It could curl a bash script to install the pre-built binaries. I would make the experience really seamless. :)

It's a feature that has been asked before, but it's not as simple as you might think. You'd need to detect what platform you're remote machine is (Windows, Mac, Linux?) and the architecture (x86? ARM?) to know what binary to install. It's also not clear where you'd put the binary (on Linux, the /usr/local/bin directory? /opt/distant/bin directory?), what permissions to use, and what account is relevant.

For now, the requirement of having the user put distant on their remote machine is reasonable to me, given it affords me time to focus on other features like adding remote terminal support to the plugin. :)
