### ISSUE TITLE
Use LSP from local

### ISSUE THREAD

**Issue by axieax** [chipsenkbeil/distant.nvim#65]
Hello,
Say Computer A is connecting to Computer B (remote). Just wondering if there is a way to configure Distant to use Computer A's LSP binaries to edit files on Computer B (displayed on Computer A using this plugin). Main reason being that there is minimal storage available for installation of any binaries on Computer B (remote). I see there are options for setting up distant.nvim in the docs, but not sure if these refer to paths on Computer A or Computer B.

**Comment by chipsenkbeil** [comment]
@axieax hey there, this isn't a feature that this plugin supports. What you're looking for is to have a virtual filesystem locally for your local LSP server to read from and write to whereas the files themselves are on another server.

While supporting a virtual filesystem may be something distant tackles in the future, your best option for now is to use something like sshfs to mount your remote files on your local machine and then point your LSP servers to those mounted files like you would with anything else local!

**Comment by axieax** [comment]
Ahh I see, thanks for the clarification. I'll have a look into sshfs now!
