### ISSUE TITLE
Heads up about clearing terminal scrollback

### ISSUE THREAD

**Issue by muniter** [chipsenkbeil/distant.nvim#67]
Hey @chipsenkbeil https://github.com/neovim/neovim/issues/15477 has been closed, letting you know you can remove https://github.com/chipsenkbeil/distant.nvim/blob/6d6be95130aa8d0e61840d71d1002cb141315d89/lua/distant/client/term.lua#L75-L79 if using the next release. Clearing the scrollback is now possible with something like:

```vim
function Terminal_clear()
  set scrollback=1
  set scrollback=10000
endfunction
```

**Comment by chipsenkbeil** [comment]
Oh, awesome! I'll be sure to do that. Haven't quite finished the branch yet before releasing it, so that feature isn't out yet. :)

**Comment by chipsenkbeil** [comment]
This is now taken care of on the upcoming 0.2 release, so closing out.
