### ISSUE TITLE
[Discussion] Go to alternate file

### ISSUE THREAD

**Issue by luanzeba** [chipsenkbeil/distant.nvim#68]
Hi, this is more of a question than an issue.

I use the [vim-rails](https://github.com/tpope/vim-rails/) plugin and one of the commands I use commonly is to open an alternate file. For example, editing the test file associated with the current open buffer. [Here are the docs associated with that command](https://github.com/tpope/vim-rails/blob/master/doc/rails.txt#L99).

When using distant and entering the command `:AV` (open alternate file in vertical split), I get the following error:
```
E492: Not an editor command: AV
```

Even though when I run `:help AV` I get access to the docs for the command.

If anyone is able to provide any pointers I'd really appreciate it! I'm brand new to distant 😄

**Comment by chipsenkbeil** [comment]
Hey, thanks for trying out the plugin! You're saying that when you have both the `vim-rails` plugin and `distant.nvim` installed, the `:AV` command that `vim-rails` provides disappears?

The buffer you're in when you run `:AV` is a distant buffer, right? Starts with `distant://path/to/file`?

**Comment by chipsenkbeil** [comment]
Closing out due to inactivity.
