### ISSUE TITLE
os error 111 when running DistantLaunch

### ISSUE THREAD

**Issue by zawedcvg** [chipsenkbeil/distant.nvim#72]
`
stack traceback:
^I[C]: in ?
^I[C]: in function 'pcall'
^I...oload/plugged/distant.nvim/lua/distant/editor/launch.lua:81: in function 'load'
^I...oload/plugged/distant.nvim/lua/distant/editor/launch.lua:67: in function 'launch'
^I...im/autoload/plugged/distant.nvim/lua/distant/command.lua:177: in function 'launch'
^I[string ":lua"]:1: in main chunk
caused by: Connection refused (os error 111)
callback error
stack traceback:
^I[C]: in ?
^I[C]: in function 'pcall'
^I...oload/plugged/distant.nvim/lua/distant/editor/launch.lua:81: in function 'load'
^I...oload/plugged/distant.nvim/lua/distant/editor/launch.lua:67: in function 'launch'
^I...im/autoload/plugged/distant.nvim/lua/distant/command.lua:177: in function 'launch'
^I[string ":lua"]:1: in main chunk
caused by: Connection refused (os error 111)
`

Running :DistantLaunch first asks for authentication and on entering the password this error pops up.

**Comment by chipsenkbeil** [comment]
@zawedcvg If you sign into your server where you are launching, is there an instance of a distant server running? My first thought is that the server was started remotely, but it started listening on a port that is not open on your server, so when attempting to connect to it after starting (through ssh), it gets a connection refused.

**Comment by zawedcvg** [comment]
So I am not the one launching the server, just connecting to it. Do I need to be using some other command? Also I can ssh into it without using distant.

**Comment by chipsenkbeil** [comment]
@zawedcvg use `DistantConnect` if you are not starting the server through the plugin.

**Comment by zawedcvg** [comment]
`callback error                                                                                                                                              
stack traceback:
^I[C]: in ?
^I[C]: in function 'pcall'
^I...load/plugged/distant.nvim/lua/distant/editor/connect.lua:52: in function 'load'
^I...load/plugged/distant.nvim/lua/distant/editor/connect.lua:38: in function 'connect'
^I...im/autoload/plugged/distant.nvim/lua/distant/command.lua:205: in function 'connect'
^I[string ":lua"]:1: in main chunk
caused by: failed to lookup address information: Name or service not known
callback error
stack traceback:
^I[C]: in ?
^I[C]: in function 'pcall'
^I...load/plugged/distant.nvim/lua/distant/editor/connect.lua:52: in function 'load'
^I...load/plugged/distant.nvim/lua/distant/editor/connect.lua:38: in function 'connect'
^I...im/autoload/plugged/distant.nvim/lua/distant/command.lua:205: in function 'connect'
^I[string ":lua"]:1: in main chunk
caused by: failed to lookup address information: Name or service not known`
This is the error caused by DistantConnect. To confirm distant key is the same as the password right? I normally connect by 
`ssh -p [port] [user]@[address]`

**Comment by chipsenkbeil** [comment]
No, key is the unique key that is printed when you run the distant server.

If you are using distant 0.15, it looks like this:

<img width="864" alt="image" src="https://user-images.githubusercontent.com/2481802/196594426-a2203b55-9e6a-49cf-83c7-f255795ab666.png">

If you are using a newer version of distant in conjunction with the updated branch, it looks like this:

<img width="877" alt="image" src="https://user-images.githubusercontent.com/2481802/196594511-4306be5d-16ba-42c0-90bb-e5a65f021c70.png">

If you are wanting to use this plugin with ssh and not the distant server, you need to set the mode to ssh.

**Comment by zawedcvg** [comment]
Alright cool works now. Thanks for the help !
