### ISSUE TITLE
Connect Failed: SecretKeyError

### ISSUE THREAD

**Issue by mkdir700** [chipsenkbeil/distant.nvim#73]
I entered the correct password, but an exception was thrown.

caused by: SecretKeyError

![iShot_2022-11-22_13 02 54](https://user-images.githubusercontent.com/56359329/203226160-2d85b30d-bd0f-4c92-a7e1-a3598dcccb13.png)

**Comment by chipsenkbeil** [comment]
This seems like an error from the old v0.1 branch of the plugin. Are you trying v0.2?

**Comment by chipsenkbeil** [comment]
If you're trying v0.1, what password are you entering? The one you should use is the one printed by the server.

```
e.g.
distant://:8ebb3eca1f4dfddd8523eb649f5e930d69b382d24d31d1e5ca2a0175b47ec84b@0.0.0.0:61600

has the key 8ebb3eca1f4dfddd8523eb649f5e930d69b382d24d31d1e5ca2a0175b47ec84b
```

**Comment by mkdir700** [comment]
> 

Thank your answer! I has switch to v0.2, but I still haven't solved the connection problem.

I entered the password and waited until the deadline has elapsed.


<img width="539" alt="image" src="https://user-images.githubusercontent.com/56359329/203249723-8d60fec8-79e4-42db-9200-0e93e64496e3.png">

**Comment by chipsenkbeil** [comment]
Closing out as an outdated issue for v0.2. With v0.3 being the new branch, feel free to open a new issue against it if this is still a problem.

My guess is that this is a case where the TCP port that distant binds to is not forwarded to be accessible outside of the machine. You may want to explicitly provide a port:

```
:DistantLaunch ssh://example.com distant.args="--port 8080"
```
