### ISSUE TITLE
 distant_lua' not found

### ISSUE THREAD

**Issue by jontan212** [chipsenkbeil/distant.nvim#74]
when I try to run ":DistantInstall" I get the following errors.
<img width="326" alt="image" src="https://user-images.githubusercontent.com/81832342/205030730-809903e3-a136-4d38-9a43-9c5d3be19444.png">

y este

<img width="396" alt="image" src="https://user-images.githubusercontent.com/81832342/205030862-6ddbd946-e4f5-4cf1-863a-b71a3286af98.png">

**Comment by chipsenkbeil** [comment]
@jontan212 can you try the `v0.2` branch instead? Not sure why the shared library is not being found after being downloaded.
