### ISSUE TITLE
Fails to connect to known host with ed25519 fingerprint

### ISSUE THREAD

**Issue by trevarj** [chipsenkbeil/distant.nvim#76]
If you have already connected to a server over ssh and saved a ssh-ed25519 fingerprint in `~/.ssh/known_host` then doing `:DistantLaunch [host name]` fails to read the fingerprint. 

```
Failed (1): Failed to launch server
Caused by:
    Fatal: host verification: host key mismatch for ssh server 192.168.1.1:22.
    Got fingerprint SHA256:7Bekk1Nx0yOKspOjOHEw+RfeaC2K9NDg51BUoVZEWBI instead of expected value from known_hosts
    file ~/.ssh/known_hosts.
```

Tried using `v0.2` branch

**Comment by chipsenkbeil** [comment]
Whoops, had a reply waiting for this and never sent it. Thanks for the port, @trevarj!

I've seen this happen and not sure why. My workaround was just to delete the entry from the known_host file and recreate it as part of `:DistantLaunch`.

You could try changing the backend that powers the ssh functionality by doing `:DistantLaunch options="ssh.backend=libssh"` and see if that helps.

**Comment by trevarj** [comment]
> My workaround was just to delete the entry from the known_host file and recreate it as part of :DistantLaunch

Yep, this is what I ended up doing too. It recreates with a ecdsa key, so my guess is the default ssh backend must be expecting only that.

**Comment by chipsenkbeil** [comment]
Closing out as an outdated issue. There's a workaround included in this issue, and this may also get resolved with https://github.com/chipsenkbeil/distant/issues/193 for distant.

Nothing else that can be done in the neovim plugin itself.
