### ISSUE TITLE
[Session(-7)] Unable to send userauth-none request

### ISSUE THREAD

**Issue by ldmax** [chipsenkbeil/distant.nvim#77]
Hi chipsenkbeil, thanks for this great plugin!

I was trying to use distant.nvim to connect from my company laptop to production server, with a jump machine in-between.

Company laptop OS: win10
Jump machine OS:

NAME="SLES"
VERSION="12-SP5"
VERSION_ID="12.5"
PRETTY_NAME="SUSE Linux Enterprise Server 12 SP5"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:12:sp5"

Production machine OS:
NAME="SLES"
VERSION="15-SP3"
VERSION_ID="15.3"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP3"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp3"
DOCUMENTATION_URL="https://documentation.suse.com/"

distant.nvim: branch v0.2 latest commit

I'm able to download Rust library on local machine and put distant-linux64-gnu-x86 to production machine ~/bin/distant/.

Here's my set up for distant:

```lua
local distant_status_ok, distant = pcall(require, "distant")
if not distant_status_ok then
  return
end

local actions = require('distant.nav.actions')

distant.setup {
  ['*'] = {
    distant = {
      args = { '--shutdown', 'lonely=60' },
      bin = '~/bin/distant/distant',
    },
    file = {
      mappings = {
        ['-'] = actions.up,
      },
    },
    dir = {
      mappings = {
        ['<Return>'] = actions.edit,
        ['-']        = actions.up,
        ['K']        = actions.mkdir,
        ['N']        = actions.newfile,
        ['R']        = actions.rename,
        ['D']        = actions.remove,
      }
    },
    ssh = {
      user = 'mxxxxxx'
    }
  },
  -- OLD PROD
  ['deda1x2699'] = {
    ssh = {
      proxy_command = "ssh nxuser -W %h:%p"
    }
  },
  -- M2 VAL
  ['deda1x3128'] = {
    ssh = {
      proxy_command = "ssh nxuser -W %h:%p"
    }
  },
  -- M2 PROD
  ['deda1x3766'] = {
    ssh = {
      proxy_command = "ssh nxuser -W %h:%p"
    }
  },
  ['deda1x3388'] = {
    ssh = {
      proxy_command = "ssh nxuser -W %h:%p"
    }
  },
  -- HPC PROD
  ['deda1x3155'] = {
    ssh = {
      proxy_command = "ssh nxuser -W %h:%p"
    }
  },
  -- HPC Test
  ['deda1x3035'] = {
    ssh = {
      proxy_command = "ssh nxuser -W %h:%p"
    }
  },
  -- M22 Test
  ['deda1x3390'] = {
    ssh = {
      proxy_command = "ssh nxuser -W %h:%p"
    }
  },
  -- R421 Test
  ['deda1x4746'] = {
    ssh = {
      proxy_command = "ssh nxuser -W %h:%p"
    }
  },
  ['deda1x4783'] = {
    ssh = {
      proxy_command = "ssh nxuser -W %h:%p"
    }
  },
  -- R421 VAL
  ['deda1x4747'] = {
    ssh = {
      proxy_command = "ssh nxuser -W %h:%p"
    }
  },
}
```

Here's what I do:
I want to connect to deda1x4746 (production machine), which requires to connect to nxuser (jump machine) first.
NOTE: ~/bin/distant/ is shared across jump machine and deda1x4746
step 1: type ":DistantLaunch deda1x4746" -- a prompt shows up (see below); I assume this is password prompt for jump machine; I entered my password three times
![image](https://user-images.githubusercontent.com/4306230/210477368-383aadd5-1ae8-4570-abcb-a59e291c1fab.png)
![image](https://user-images.githubusercontent.com/4306230/210477427-51cebce3-03ff-42bd-aa13-49c8b0fbd141.png)
![image](https://user-images.githubusercontent.com/4306230/210477471-b8aa0626-9a72-46da-b4bf-26ef1642df7c.png)

step 2: another prompt asking me to enter password for deda1x4746 shows up; I entered password for deda1x4746 once; an error message shows up (see below)
![image](https://user-images.githubusercontent.com/4306230/210477578-2a9f2e4c-1c65-4f8b-a95e-c5d1e10f3e6d.png)
![image](https://user-images.githubusercontent.com/4306230/210477606-7a5066d8-e246-4a89-a0f9-9b6ac5e64f3e.png)

I also tried :DistantConnect deda1x4746:22, I got
![image](https://user-images.githubusercontent.com/4306230/210484046-25070430-e3ca-40bd-a857-67e3c4e21572.png)

Would it be possible that you could give me some advice? Thanks!

**Comment by chipsenkbeil** [comment]
@ldmax thank you for the detailed report! I've not actually tried a jump host before. Does the final result require you to tunnel traffic through `nxuser` once the distant server has been spawned? Or would you be connecting via TCP directly from your laptop to `deda1x4746` and other instances?

If it's the former, then you'd want to use `DistantConnect ssh://...` to only use ssh and not the distant server itself as distant does not (yet) support tunneling TCP connections. Even with that, there may be an issue with the ssh backend we use (there are two different backends available), and you can try changing the backend during `DistantConnect options="ssh.backend=libssh"` IIRC.

**Comment by chipsenkbeil** [comment]
Closing out as an outdated issue. You can try switching the ssh library to `libssh` as mentioned above. This may also get resolved with https://github.com/chipsenkbeil/distant/issues/193 for distant.

Nothing else that can be done in the neovim plugin itself.
