### ISSUE TITLE
DistantOpen not displaying files in directory

### ISSUE THREAD

**Issue by dallasclarke** [chipsenkbeil/distant.nvim#78]
After connecting to my remote server using ssh mode, when I run `:DistantOpen /file1/file2`  or `:DistantOpen .` nothing appears at all.

**Comment by chipsenkbeil** [comment]
@dallasclarke which version of distant.nvim are you using? The main branch? Or the v0.2 branch?

Does anything show up under `:messages`? Anything in `~/.cache/nvim/distant*.log` files?

**Comment by dallasclarke** [comment]
Not to sure about version, whatever Packer would've installed. When I run `:messages` after running `DistantLaunch` it shows my directories on my remote server & nothing in the log files.

**Comment by chipsenkbeil** [comment]
Closing out as an outdated issue. You can try the v0.3 branch to see if it resolves any issues.
