### ISSUE TITLE
Host-specific settings not loading

### ISSUE THREAD

**Issue by pjedynak** [chipsenkbeil/distant.nvim#80]
I was trying to switch to distant.nvim v0.2, but I noticed that LSP is not started (distant.nvim -> v0.2, distant -> 0.20.0). I haven't had any problems in previous version distant.nvim 0.1.1 and distant 0.15.1. Is it known bug or maybe I have some problem with configuration. I haven't changed anything in configuration in comparison to v0.1.1.

My configuration:
```
require('distant').setup {
    -- Applies Chip's personal settings to every machine you connect to
    --
    -- 1. Ensures that distant servers terminate with no connections
    -- 2. Provides navigation bindings for remote directories
    -- 3. Provides keybinding to jump into a remote file's parent directory
    ['*'] = require('distant.settings').chip_default(),

    ['localhost'] = {
        distant = {
            bin = '/distant',
        },
        lsp = {
            ['cpp'] = {
                cmd = { 'clangd', '--background-index', "--compile-commands-dir=build" },
                filetypes = { 'c', 'cpp' },
                root_dir = '/mnt',
                on_attach = function()
                    nnoremap('gD', '<CMD>lua vim.lsp.buf.declaration()<CR>')
                    nnoremap('gd', '<CMD>lua vim.lsp.buf.definition()<CR>')
                    nnoremap('gh', '<CMD>lua vim.lsp.buf.hover()<CR>')
                    nnoremap('gi', '<CMD>lua vim.lsp.buf.implementation()<CR>')
                    nnoremap('gr', '<CMD>lua vim.lsp.buf.references()<CR>')
                end,
            },
        },
    },
}

**Comment by chipsenkbeil** [comment]
I'm not aware of LSP being broken on the branch as it still passes the tests we have to validate it.

Can you verify that the LSP client is not attached to your buffer? Also, what do the logs say regarding LSP usage?

You can set the environment variables `DISTANT_LOG_LEVEL` to trace and `DISTANT_LOG_FILE` to something like `/tmp/distant.nvim.log` to get full log output.

I'd expect to see log output like

```
lsp.connect(4)
File /mnt/to/file is within /mnt of cpp
File /mnt/to/file of type ft applies to cpp
Starting LSP cpp
Attaching to buf 4 for LSP cpp
```

Trying to narrow down if this is an issue with the LSP not starting, the LSP client not attaching to the buffer, or something else.

You can also set neovim's general LSP log level and output using stuff like `vim.lsp.log.set_level()` and find the file via `vim.lsp.log.get_filename()` from [vim.lsp.log](https://neovim.io/doc/user/lsp.html#lsp-log).

If this all looks okay, then we'd want to get logs from the distant server, manager, and client to make sure that they are properly forwarding traffic between your computer and the LSP process.

**Comment by pjedynak** [comment]
Unfortunatelly there isn't any try a connection to lsp:
```
[DEBUG pią, 17 lut 2023, 20:56:56] ...ite/pack/packer/start/distant.nvim/lua/distant/state.lua:74: Manager not listening, so starting process
[DEBUG pią, 17 lut 2023, 20:56:56] ...ck/packer/start/distant.nvim/lua/distant/cli/manager.lua:399: Connecting with options: {
  destination = "localhost:36711"
}
[DEBUG pią, 17 lut 2023, 20:56:56] ...ck/packer/start/distant.nvim/lua/distant/cli/manager.lua:426: Connect cmd: { "/home/jedyny/.local/share/nvim/distant.nvim/bin/distant", "client", "connect", "--unix-socket", "/home/jedyny/.cache/nvim/distant.nvim/nvim-8034.sock", "--windows-pipe", "nvim-2717", "--format", "json", "localhost:36711" }
[DEBUG pią, 17 lut 2023, 20:57:14] ...ck/packer/start/distant.nvim/lua/distant/editor/open.lua:431: retrieved path info for "/mnt"
[DEBUG pią, 17 lut 2023, 20:57:14] ...ck/packer/start/distant.nvim/lua/distant/editor/open.lua:435: does buf "distant:///mnt" exist? "no"
[DEBUG pią, 17 lut 2023, 20:57:14] ...ck/packer/start/distant.nvim/lua/distant/editor/open.lua:474: loaded "/mnt" into buf 2
[DEBUG pią, 17 lut 2023, 20:57:14] ...e/pack/packer/start/distant.nvim/lua/distant/autocmd.lua:17: buf 2 is not initialized, so triggering BufReadCmd
[DEBUG pią, 17 lut 2023, 20:57:14] ...e/pack/packer/start/distant.nvim/lua/distant/autocmd.lua:42: Reading "/mnt" into buf 2
[DEBUG pią, 17 lut 2023, 20:57:14] ...ck/packer/start/distant.nvim/lua/distant/editor/open.lua:431: retrieved path info for "/mnt"
[DEBUG pią, 17 lut 2023, 20:57:14] ...ck/packer/start/distant.nvim/lua/distant/editor/open.lua:435: does buf "distant:///mnt" exist? "yes"
[DEBUG pią, 17 lut 2023, 20:57:15] ...ck/packer/start/distant.nvim/lua/distant/editor/open.lua:474: loaded "/mnt" into buf 2
[DEBUG pią, 17 lut 2023, 20:57:39] ...ck/packer/start/distant.nvim/lua/distant/editor/open.lua:431: retrieved path info for "/mnt/src"
[DEBUG pią, 17 lut 2023, 20:57:39] ...ck/packer/start/distant.nvim/lua/distant/editor/open.lua:435: does buf "distant:///mnt/src" exist? "no"
[DEBUG pią, 17 lut 2023, 20:57:39] ...ck/packer/start/distant.nvim/lua/distant/editor/open.lua:474: loaded "/mnt/src" into buf 3
[DEBUG pią, 17 lut 2023, 20:57:49] ...ck/packer/start/distant.nvim/lua/distant/editor/open.lua:431: retrieved path info for "/mnt/src/simple.cpp"
[DEBUG pią, 17 lut 2023, 20:57:49] ...ck/packer/start/distant.nvim/lua/distant/editor/open.lua:435: does buf "distant:///mnt/src/simple.cpp" exist? "no"
[DEBUG pią, 17 lut 2023, 20:57:49] ...ck/packer/start/distant.nvim/lua/distant/editor/open.lua:474: loaded "/mnt/src/simple.cpp" into buf 4

```
In lsp log there doesn't exist any entry, so it denotes that distant haven't been trying to establish connection with lsp. Do you have any idea what can be wrong ? 
Also in client.log and manager.log I cannot see any things regarding lsp.

I want to highlight that with version 0.1.1 everything was working correctly.

**Comment by pjedynak** [comment]
Ok It looks that in newer version it doesn't get my confguration for localhost, when I've configured everything under '*' then it has started correctly lsp server.

**Comment by chipsenkbeil** [comment]
Good catch. I'll look through the commits to see what changed and get a fix out for you to try.

**Comment by chipsenkbeil** [comment]
@pjedynak out of curiosity, did you try setting the server to be `127.0.0.1` instead of `localhost` to see if it worked?

**Comment by chipsenkbeil** [comment]
Okay, identified the bug, so need to get a fix out.

If I do something like `DistantConnect distant://:{password}@{host}:{port}`, the entire destination is passed as the label instead of just the host for matching purposes. We don't use any kind of partial matching (only exact match), so unless we just pass in the host, this will cause all of the host-specific configurations to not match.

Marking this issue as a bug to resolve.

**Comment by chipsenkbeil** [comment]
Should be resolved via https://github.com/chipsenkbeil/distant.nvim/commit/6647d4e0f1b1e2c62327356c4c128936a4b464ff.

Tested it myself and it now parses the destination to extract the host and use that for the settings.
