### ISSUE TITLE
Agent forwarding

### ISSUE THREAD

**Issue by anatoly-kor** [chipsenkbeil/distant.nvim#81]
Is it possible to connect through ssh with agent forwarding?

**Comment by chipsenkbeil** [comment]
Not at this time, no. If it was available, how would you expect ssh forwarding to work in conjunction with this plugin? What would you want to be able to do?

**Comment by anatoly-kor** [comment]
I don't know how exactly it work in vscode, but it work just through ssh command. Just ask password 2 times.

**Comment by chipsenkbeil** [comment]
Closing out for now. If you'd like to flesh out this idea, feel free to open a discussion in the ideas section: https://github.com/chipsenkbeil/distant.nvim/discussions/categories/ideas
