### ISSUE TITLE
Support for Termux

### ISSUE THREAD

**Issue by ayoubelmhamdi** [chipsenkbeil/distant.nvim#83]
I am encountering issues when building crates in Termux, as rustup `stable-aarch64-linux-android` is not fully supported in this environment. I think it would be helpful if `distant.nvim` could add support for Termux, as this would enable users to easily use remote Rust development features from their Android devices.

Thank you for your consideration.

**Comment by chipsenkbeil** [comment]
Hi @ayoubelmhamdi! Does termux support neovim? If so, have you tried compiling the distant binary to see if it will run on `stable-aarch64-linux-android`? I'm not at a computer that can support that target right now. If neovim works and the distant binary can be compiled on that platform, then you can use it to communicate with remote machines from termux.

If it doesn't compile, can you file an issue over at https://github.com/chipsenkbeil/distant with the compilation error(s) you encounter?

**Comment by ayoubelmhamdi** [comment]
`termux` is an android app that emulates Linux functionality. It has a package manager (similar to Debian apt) and many applications. However, it does not have the distant binary in Termux.

**Comment by chipsenkbeil** [comment]
@ayoubelmhamdi thanks for reporting. I've commented on the issue in distant that you filed, which is https://github.com/chipsenkbeil/distant/issues/163.

I'm going to close out this issue as the limitation is on the side of distant and not this neovim plugin. So we can discuss further and resolve over there!
